name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      - name: Create Environment File
        run: |
          echo ${{ secrets.ENV_FILE }} > .env

      - name: Verify Environment File
        run: |
          cat .env
          echo "Environment file created."

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          exec -l $SHELL
          echo "${{ secrets.SERVICE_ACCOUNT }}" > /tmp/service-account.json
          gcloud auth login
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud auth activate-service-account --key-file=/tmp/service-account.json

      - name: Deploy to App Engine
        run: |
          gcloud app deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT }}
